      module cxk_I
      interface
!...Generated by Pacific-Sierra Research 77to90  4.3E  06:33:54  12/28/06
!...Modified by Charlotte Froese Fischer
!                     Gediminas Gaigalas  10/05/17
      subroutine cxk (S, IS, KAPS, NU, K, IBR, IEX)
      use iso_fortran_env, only: real64, int32, int64, real128
      real(real64), dimension(12), INTENT(INOUT) :: S
      integer, dimension(4), intent(in) :: IS
      integer, dimension(4), intent(in) :: KAPS
      integer, intent(in) :: NU
      integer, intent(in) :: K
      integer, intent(in) :: IBR
      integer, intent(in) :: IEX
!VAST...Calls: CRE
!...This routine performs I/O.
      end subroutine
      end interface
      end module
