      MODULE cxk_I
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  06:33:54  12/28/06
!...Modified by Charlotte Froese Fischer
!                     Gediminas Gaigalas  10/05/17
      SUBROUTINE cxk (S, IS, KAPS, NU, K, IBR, IEX)
      use iso_fortran_env, only: real64, int32, int64, real128
      real(real64), DIMENSION(12), INTENT(INOUT) :: S
      INTEGER, DIMENSION(4), INTENT(IN) :: IS
      INTEGER, DIMENSION(4), INTENT(IN) :: KAPS
      INTEGER, INTENT(IN) :: NU
      INTEGER, INTENT(IN) :: K
      INTEGER, INTENT(IN) :: IBR
      INTEGER, INTENT(IN) :: IEX
!VAST...Calls: CRE
!...This routine performs I/O.
      END SUBROUTINE
      END INTERFACE
      END MODULE
