      module talk_I
      interface
!...Generated by Pacific-Sierra Research 77to90  4.3E  15:16:29   1/ 6/07
!...Modified by Charlotte Froese Fischer
!                     Gediminas Gaigalas  10/05/17
      subroutine talk (JA, JB, NU, IA, IB, IC, ID, ITYPE, COEF)
      use iso_fortran_env, only: real64, int32, int64, real128
      integer, intent(in) :: JA
      integer, intent(in) :: JB
      integer, intent(in) :: NU
      integer, intent(in) :: IA
      integer, intent(in) :: IB
      integer, intent(in) :: IC
      integer, intent(in) :: ID
      integer, intent(in) :: ITYPE
      real(kind=real64), intent(in) :: COEF
!VAST.../BUFFER/ NBDIM(IN), NVCOEF(INOUT)
!VAST.../DEBUG/ IBUG1(IN)
!VAST.../ORB4/ NP(IN)
!VAST.../ORB10/ NH(IN)
!VAST...Calls: ALCBUF
!...This routine performs I/O.
      end subroutine
      end interface
      end module
