      MODULE engout_I
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  10:47:24   2/14/04
!...Modified by Charlotte Froese Fischer
!                     Gediminas Gaigalas  11/02/17
      SUBROUTINE engout (EAV, E, JTOT, IPAR, ILEV, NN, MODE)
      use iso_fortran_env, only: real64, int32, int64, real128
      real(real64), INTENT(IN) :: EAV
      real(real64), DIMENSION(NN), INTENT(IN) :: E
      INTEGER, DIMENSION(NN), INTENT(IN) :: JTOT
      INTEGER, DIMENSION(NN), INTENT(IN) :: IPAR
      INTEGER, DIMENSION(NN), INTENT(IN) :: ILEV
      INTEGER, INTENT(IN) :: NN
      INTEGER, INTENT(IN) :: MODE
      END SUBROUTINE
      END INTERFACE
      END MODULE
