      module getmixblock_I
  use iso_fortran_env, only: real64
      interface
!...Generated by Pacific-Sierra Research 77to90  4.3E  18:32:57   1/ 6/07
!...Modified by Charlotte Froese Fischer
!                     Gediminas Gaigalas  11/01/17
      subroutine getmixblock (NAME, NCI)
      character (LEN = 24), intent(in) :: NAME
      integer, intent(in) :: NCI
      end subroutine
      end interface
      end module
