      module getsmd_I
      interface
!...Generated by Pacific-Sierra Research 77to90  4.3E  06:40:03  12/28/06
!...Modified by Charlotte Froese Fischer
!                     Gediminas Gaigalas  11/02/17
      subroutine getsmd (NAME)
      character (LEN = 24), intent(in) :: NAME
      end subroutine
      end interface
      end module
