      module polint_I
      use iso_fortran_env, only: real64
      interface
!...Generated by Pacific-Sierra Research 77to90  4.3E  06:40:03  12/28/06
!...Modified by Charlotte Froese Fischer
!                     Gediminas Gaigalas  11/02/17
      subroutine polint (XA, YA, DENS)
      use iso_fortran_env, only: real64, int32, int64, real128
      real(kind=real64), dimension(3), intent(in) :: XA
      real(kind=real64), dimension(3), intent(in) :: YA
      real(kind=real64), intent(out) :: DENS
      end subroutine
      end interface
      end module
