      MODULE polint_I
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  06:40:03  12/28/06
!...Modified by Charlotte Froese Fischer
!                     Gediminas Gaigalas  11/02/17
      SUBROUTINE polint (XA, YA, DENS)
      use iso_fortran_env, only: real64, int32, int64, real128
      real(real64), DIMENSION(3), INTENT(IN) :: XA
      real(real64), DIMENSION(3), INTENT(IN) :: YA
      real(real64), INTENT(OUT) :: DENS
      END SUBROUTINE
      END INTERFACE
      END MODULE
