      module setdbg_I
  use iso_fortran_env, only: real64
      interface
!...Generated by Pacific-Sierra Research 77to90  4.3E  06:36:34  12/28/06
!...Modified by Charlotte Froese Fischer
!                     Gediminas Gaigalas  11/01/17
      subroutine setdbg
      end subroutine
      end interface
      end module
