      module setsum_I
      interface
!...Generated by Pacific-Sierra Research 77to90  4.3E  06:36:34  12/28/06
!...Modified by Charlotte Froese Fischer
!                     Gediminas Gaigalas  11/01/17
      subroutine setsum (NAME, NCI)
      character (LEN = 24), intent(in) :: NAME
      integer, intent(in) :: NCI
      end subroutine
      end interface
      end module
