      module vinti_I
      use iso_fortran_env, only: real64
      interface
!...Generated by Pacific-Sierra Research 77to90  4.3E  06:40:03  12/28/06
!...Modified by Charlotte Froese Fischer
!                     Gediminas Gaigalas  11/02/17
      real(kind=real64) FUNCTION vinti (J, K)
      integer, intent(in) :: J
      integer, intent(in) :: K
      END FUNCTION
      end interface
      end module
