      MODULE adds_I
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  20:12:31   2/12/04
!...Modified by Charlotte Froese Fischer
!                     Gediminas Gaigalas  10/05/17
      SUBROUTINE adds (N, LIM, KPASS, NNCV, BASIS, AB, S)
      use iso_fortran_env, only: real64, int32, int64, real128
      INTEGER, INTENT(IN) :: N
      INTEGER, INTENT(IN) :: LIM
      INTEGER, INTENT(IN) :: KPASS
      INTEGER, INTENT(IN) :: NNCV
      real(real64), DIMENSION(N*LIM) :: BASIS
      real(real64), DIMENSION(N*LIM) :: AB
      real(real64), DIMENSION(LIM*(LIM + 1)/2), INTENT(OUT) :: S
!VAST...Calls: DDOT
      END SUBROUTINE
      END INTERFACE
      END MODULE
