      module adds_I
      interface
!...Generated by Pacific-Sierra Research 77to90  4.3E  20:12:31   2/12/04
!...Modified by Charlotte Froese Fischer
!                     Gediminas Gaigalas  10/05/17
      subroutine adds (N, LIM, KPASS, NNCV, BASIS, AB, S)
      use iso_fortran_env, only: real64, int32, int64, real128
      integer, intent(in) :: N
      integer, intent(in) :: LIM
      integer, intent(in) :: KPASS
      integer, intent(in) :: NNCV
      real(real64), dimension(N*LIM) :: BASIS
      real(real64), dimension(N*LIM) :: AB
      real(real64), dimension(LIM*(LIM + 1)/2), intent(out) :: S
!VAST...Calls: DDOT
      end subroutine
      end interface
      end module
