      module dvdrvr_I
      interface
!...Generated by Pacific-Sierra Research 77to90  4.3E  20:12:31   2/12/04
!...Modified by Charlotte Froese Fischer
!                     Gediminas Gaigalas  10/05/17
      subroutine dvdrvr (IRC, IREV, N, HIEND, LIM, MBLOCK, NOC, NUME, NIV, NEIG&
         , ISELEC, CRITE, CRITC, CRITR, MAXITER, EIGVAL, BASIS, ORTHOBASIS, AB&
         , S, TEMPS, SVEC, SCRA1, ISCRA2, INCV, ICV, OLDVAL, NLOOPS, IERR)
      use iso_fortran_env, only: real64, int32, int64, real128
      integer, INTENT(INOUT) :: IRC
      integer, dimension(*), intent(out) :: IREV
      integer, intent(in) :: N
      logical, intent(in) :: HIEND
      integer, intent(in) :: LIM
      integer :: MBLOCK
      integer, intent(in) :: NOC
      integer, intent(in) :: NUME
      integer, intent(in) :: NIV
      integer, intent(in) :: NEIG
      integer, dimension(NEIG) :: ISELEC
      real(real64) :: CRITE
      real(real64) :: CRITC
      real(real64) :: CRITR
      integer, intent(in) :: MAXITER
      real(real64), dimension(LIM), INTENT(INOUT) :: EIGVAL
      real(real64), dimension(N*LIM) :: BASIS
      real(real64), dimension(N*LIM + NOC*N) :: ORTHOBASIS
      real(real64), dimension(N*LIM) :: AB
      real(real64), dimension(LIM*(LIM + 1)/2) :: S
      real(real64), dimension(LIM*(LIM + 1)/2) :: TEMPS
      real(real64), dimension(LIM*LIM) :: SVEC
      real(real64), dimension(8*LIM), INTENT(INOUT) :: SCRA1
      integer, dimension(5*LIM) :: ISCRA2
      integer, dimension(LIM), intent(in) :: INCV
      integer, dimension(NUME + 1), intent(out) :: ICV
      real(real64), dimension(NUME + 1), INTENT(INOUT) :: OLDVAL
      integer, INTENT(INOUT) :: NLOOPS
      integer, INTENT(INOUT) :: IERR
!VAST.../MPI/ MYID(IN)
!VAST...Calls: TSTSEL, SLAMCH, DCOPY, DSPEVX, OVFLOW, NEWVEC
!VAST...Calls: DSCAL, MGS_NRM, ADDS, MULTBC, DAXPY, DDOT
!...This routine performs I/O.
      end subroutine
      end interface
      end module
