      module gdvd_I
      interface
!...Generated by Pacific-Sierra Research 77to90  4.3E  20:12:31   2/12/04
!...Modified by Charlotte Froese Fischer
!                     Gediminas Gaigalas  10/05/17
      subroutine gdvd (OP, N, LIM, DIAG, ILOW, IHIGH, ISELEC, NIV, MBLOCK&
         , CRITE, CRITC, CRITR, ORTHO, MAXITER, WORK, IWRSZ, IWORK, IIWSZ&
         , HIEND, NLOOPS, NMV, IERR)
      use iso_fortran_env, only: real64, int32, int64, real128
      EXTERNAL OP
      integer, intent(in) :: N
      integer, intent(in) :: LIM
      real(kind=real64), dimension(N), INTENT(INOUT) :: DIAG
      integer :: ILOW
      integer :: IHIGH
      integer, dimension(LIM) :: ISELEC
      integer, intent(in) :: NIV
      integer :: MBLOCK
      real(kind=real64) :: CRITE
      real(kind=real64) :: CRITC
      real(kind=real64) :: CRITR
      real(kind=real64) :: ORTHO
!VAST...Dummy argument ORTHO is not referenced in this routine.
      integer :: MAXITER
      real(kind=real64), dimension(IWRSZ), INTENT(INOUT) :: WORK
      integer, intent(in) :: IWRSZ
      integer, dimension(IIWSZ), intent(in) :: IWORK
      integer, intent(in) :: IIWSZ
      logical :: HIEND
      integer :: NLOOPS
      integer, intent(out) :: NMV
      integer, intent(out) :: IERR
!VAST...Calls: OP, DVDSON
!...This routine performs I/O.
      end subroutine
      end interface
      end module
