      MODULE initdvd_I
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  20:12:31   2/12/04
!...Modified by Charlotte Froese Fischer
!                     Gediminas Gaigalas  10/05/17
      SUBROUTINE initdvd (IRC, IREV, N, NOC, NIV, NUME, LIM, HIEND, SCRA1&
         , ORTHOBASIS, BASIS, AB, S)
      use iso_fortran_env, only: real64, int32, int64, real128
      INTEGER, INTENT(INOUT) :: IRC
      INTEGER, DIMENSION(*), INTENT(OUT) :: IREV
      INTEGER, INTENT(IN) :: N
      INTEGER, INTENT(IN) :: NOC
      INTEGER, INTENT(INOUT) :: NIV
      INTEGER, INTENT(IN) :: NUME
      INTEGER, INTENT(IN) :: LIM
      LOGICAL, INTENT(IN) :: HIEND
      real(real64), DIMENSION(*) :: SCRA1
      real(real64), DIMENSION(N*(NOC + LIM)) :: ORTHOBASIS
      real(real64), DIMENSION(N*LIM) :: BASIS
      real(real64), DIMENSION(N*LIM) :: AB
      real(real64), DIMENSION(*) :: S
!VAST...Calls: DINIT, DCOPY, MGS_NRM, DSCAL, ADDS
      END SUBROUTINE
      END INTERFACE
      END MODULE
