      module initdvd_I
      interface
!...Generated by Pacific-Sierra Research 77to90  4.3E  20:12:31   2/12/04
!...Modified by Charlotte Froese Fischer
!                     Gediminas Gaigalas  10/05/17
      subroutine initdvd (IRC, IREV, N, NOC, NIV, NUME, LIM, HIEND, SCRA1&
         , ORTHOBASIS, BASIS, AB, S)
      use iso_fortran_env, only: real64, int32, int64, real128
      integer, INTENT(INOUT) :: IRC
      integer, dimension(*), intent(out) :: IREV
      integer, intent(in) :: N
      integer, intent(in) :: NOC
      integer, INTENT(INOUT) :: NIV
      integer, intent(in) :: NUME
      integer, intent(in) :: LIM
      logical, intent(in) :: HIEND
      real(real64), dimension(*) :: SCRA1
      real(real64), dimension(N*(NOC + LIM)) :: ORTHOBASIS
      real(real64), dimension(N*LIM) :: BASIS
      real(real64), dimension(N*LIM) :: AB
      real(real64), dimension(*) :: S
!VAST...Calls: DINIT, DCOPY, MGS_NRM, DSCAL, ADDS
      end subroutine
      end interface
      end module
