      module mgs_nrm_I
      interface
!...Generated by Pacific-Sierra Research 77to90  4.3E  20:12:31   2/12/04
!...Modified by Charlotte Froese Fischer
!                     Gediminas Gaigalas  10/05/17
      subroutine mgs_nrm (N, KP, NEW, SCRA, B)
      use iso_fortran_env, only: real64, int32, int64, real128
      integer, intent(in) :: N
      integer, intent(in) :: KP
      integer, intent(in) :: NEW
      real(kind=real64), dimension(NEW), intent(in) :: SCRA
      real(kind=real64), dimension((KP + NEW)*N), INTENT(INOUT) :: B
!VAST...Calls: DGEMV, DDOT, DSCAL
      end subroutine
      end interface
      end module
