      module multbc_I
      interface
!...Generated by Pacific-Sierra Research 77to90  4.3E  20:12:31   2/12/04
!...Modified by Charlotte Froese Fischer
!                     Gediminas Gaigalas  10/05/17
      subroutine multbc (N, K, M, C, TEMP, B)
      use iso_fortran_env, only: real64, int32, int64, real128
      integer, intent(in) :: N
      integer, intent(in) :: K
      integer, intent(in) :: M
      real(kind=real64), dimension(K*M) :: C
      real(kind=real64), dimension(M) :: TEMP
      real(kind=real64), dimension(N*K) :: B
!VAST...Calls: DGEMV, DCOPY
      end subroutine
      end interface
      end module
