      MODULE multbc_I
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  20:12:31   2/12/04
!...Modified by Charlotte Froese Fischer
!                     Gediminas Gaigalas  10/05/17
      SUBROUTINE multbc (N, K, M, C, TEMP, B)
      use iso_fortran_env, only: real64, int32, int64, real128
      INTEGER, INTENT(IN) :: N
      INTEGER, INTENT(IN) :: K
      INTEGER, INTENT(IN) :: M
      real(real64), DIMENSION(K*M) :: C
      real(real64), DIMENSION(M) :: TEMP
      real(real64), DIMENSION(N*K) :: B
!VAST...Calls: DGEMV, DCOPY
      END SUBROUTINE
      END INTERFACE
      END MODULE
