      MODULE newvec_I
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  20:12:31   2/12/04
!...Modified by Charlotte Froese Fischer
!                     Gediminas Gaigalas  10/05/17
      SUBROUTINE newvec (N, NUME, LIM, MBLOCK, KPASS, CRITR, NNCV, INCV, SVEC&
         , EIGVAL, OLDVAL, AB, BASIS, ICV, SCRA1, EPSIL, DONE)
      use iso_fortran_env, only: real64, int32, int64, real128
      INTEGER, INTENT(IN) :: N
      INTEGER, INTENT(IN) :: NUME
      INTEGER, INTENT(IN) :: LIM
      INTEGER, INTENT(IN) :: MBLOCK
      INTEGER, INTENT(IN) :: KPASS
      real(real64), INTENT(IN) :: CRITR
      INTEGER, INTENT(INOUT) :: NNCV
      INTEGER, DIMENSION(NUME), INTENT(INOUT) :: INCV
      real(real64), DIMENSION(LIM*NUME) :: SVEC
      real(real64), DIMENSION(LIM), INTENT(IN) :: EIGVAL
      real(real64), DIMENSION(NUME), INTENT(IN) :: OLDVAL
      real(real64), DIMENSION(N*LIM) :: AB
      real(real64), DIMENSION(N*LIM) :: BASIS
      INTEGER, DIMENSION(NUME), INTENT(OUT) :: ICV
      real(real64), DIMENSION(LIM), INTENT(INOUT) :: SCRA1
      real(real64), DIMENSION(LIM), INTENT(OUT) :: EPSIL
      LOGICAL, INTENT(OUT) :: DONE
!VAST.../MPI/ MYID(IN)
!VAST...Calls: DGEMV, DAXPY, DDOT
!...This routine performs I/O.
      END SUBROUTINE
      END INTERFACE
      END MODULE
