      module ovflow_I
      interface
!...Generated by Pacific-Sierra Research 77to90  4.3E  20:12:31   2/12/04
!...Modified by Charlotte Froese Fischer
!                     Gediminas Gaigalas  10/05/17
      subroutine ovflow (N, NUME, KPASS, SCRA1, BASIS, AB, S, SVEC, EIGVAL)
      use iso_fortran_env, only: real64, int32, int64, real128
      integer, intent(in) :: N
      integer, intent(in) :: NUME
      integer, INTENT(INOUT) :: KPASS
!CFF   .. added dimension to scra1
      real(real64) :: SCRA1(NUME)
      real(real64), dimension(N*KPASS) :: BASIS
      real(real64), dimension(N*KPASS) :: AB
      real(real64), dimension((KPASS*(KPASS + 1))/2), intent(out) :: S
      real(real64), dimension(KPASS), intent(in) :: EIGVAL
!VAST...Calls: MULTBC, DINIT
      end subroutine
      end interface
      end module
