      MODULE ovflow_I
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  20:12:31   2/12/04
!...Modified by Charlotte Froese Fischer
!                     Gediminas Gaigalas  10/05/17
      SUBROUTINE ovflow (N, NUME, KPASS, SCRA1, BASIS, AB, S, SVEC, EIGVAL)
      use iso_fortran_env, only: real64, int32, int64, real128
      INTEGER, INTENT(IN) :: N
      INTEGER, INTENT(IN) :: NUME
      INTEGER, INTENT(INOUT) :: KPASS
!CFF   .. added dimension to scra1
      real(real64) :: SCRA1(NUME)
      real(real64), DIMENSION(N*KPASS) :: BASIS
      real(real64), DIMENSION(N*KPASS) :: AB
      real(real64), DIMENSION((KPASS*(KPASS + 1))/2), INTENT(OUT) :: S
      real(real64), DIMENSION(KPASS), INTENT(IN) :: EIGVAL
!VAST...Calls: MULTBC, DINIT
      END SUBROUTINE
      END INTERFACE
      END MODULE
