      MODULE tstsel_I
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  20:12:31   2/12/04
!...Modified by Charlotte Froese Fischer
!                     Gediminas Gaigalas  10/05/17
      LOGICAL FUNCTION tstsel (KPASS, NUME, NEIG, ISELEC, SVEC, EIGVAL, ICV&
         , CRITE, CRITC, ROWLAST, IND, OLDVAL, NNCV, INCV)
      use iso_fortran_env, only: real64, int32, int64, real128
      INTEGER, INTENT(IN) :: KPASS
      INTEGER, INTENT(IN) :: NUME
      INTEGER, INTENT(IN) :: NEIG
      INTEGER, DIMENSION(NEIG), INTENT(IN) :: ISELEC
      real(real64), DIMENSION(KPASS*NUME), INTENT(IN) :: SVEC
      real(real64), DIMENSION(NUME), INTENT(IN) :: EIGVAL
      INTEGER, DIMENSION(NUME), INTENT(OUT) :: ICV
      real(real64), INTENT(IN) :: CRITE
      real(real64), INTENT(IN) :: CRITC
      real(real64), DIMENSION(NEIG), INTENT(INOUT) :: ROWLAST
      INTEGER, DIMENSION(NEIG), INTENT(INOUT) :: IND
      real(real64), DIMENSION(NUME), INTENT(IN) :: OLDVAL
      INTEGER, INTENT(INOUT) :: NNCV
      INTEGER, DIMENSION(NEIG), INTENT(OUT) :: INCV
!VAST.../MPI/ MYID(IN)
!VAST...Calls: IDAMAX
!...This routine performs I/O.
      END FUNCTION
      END INTERFACE
      END MODULE
