      module tstsel_I
      interface
!...Generated by Pacific-Sierra Research 77to90  4.3E  20:12:31   2/12/04
!...Modified by Charlotte Froese Fischer
!                     Gediminas Gaigalas  10/05/17
      logical FUNCTION tstsel (KPASS, NUME, NEIG, ISELEC, SVEC, EIGVAL, ICV&
         , CRITE, CRITC, ROWLAST, IND, OLDVAL, NNCV, INCV)
      use iso_fortran_env, only: real64, int32, int64, real128
      integer, intent(in) :: KPASS
      integer, intent(in) :: NUME
      integer, intent(in) :: NEIG
      integer, dimension(NEIG), intent(in) :: ISELEC
      real(real64), dimension(KPASS*NUME), intent(in) :: SVEC
      real(real64), dimension(NUME), intent(in) :: EIGVAL
      integer, dimension(NUME), intent(out) :: ICV
      real(real64), intent(in) :: CRITE
      real(real64), intent(in) :: CRITC
      real(real64), dimension(NEIG), INTENT(INOUT) :: ROWLAST
      integer, dimension(NEIG), INTENT(INOUT) :: IND
      real(real64), dimension(NUME), intent(in) :: OLDVAL
      integer, INTENT(INOUT) :: NNCV
      integer, dimension(NEIG), intent(out) :: INCV
!VAST.../MPI/ MYID(IN)
!VAST...Calls: IDAMAX
!...This routine performs I/O.
      END FUNCTION
      end interface
      end module
