      module ixjtik_I
      interface
!...Generated by Pacific-Sierra Research 77to90 4.3E  10:05:49  11/16/01
      integer FUNCTION ixjtik (I, J, K, L, M, N)
      integer :: I
      integer :: J
      integer :: K
      integer :: L
      integer :: M
      integer :: N
!VAST...Calls: ITTK
      END FUNCTION
      end interface
      end module
