      module nine0_I
      interface
!...Generated by Pacific-Sierra Research 77to90 4.3E  10:07:58  11/16/01
      subroutine nine0 (J1, J2, J3, L1, L2, L3, K1, K2, K3, AA)
      use iso_fortran_env, only: real64, int32, int64, real128
      integer, intent(in) :: J1
      integer, intent(in) :: J2
      integer, intent(in) :: J3
      integer, intent(in) :: L1
      integer, intent(in) :: L2
      integer, intent(in) :: L3
      integer, intent(in) :: K1
      integer, intent(in) :: K2
      integer, intent(in) :: K3
      real(kind=real64), intent(out) :: AA
!VAST.../CONSTS/ ZERO(IN), ONE(IN)
!VAST...Calls: SIXJ
      end subroutine
      end interface
      end module
