      module sixj_I
      interface
!...Generated by Pacific-Sierra Research 77to90 4.3E  10:06:26  11/16/01
      subroutine sixj (I, J, K, L, M, N, ITIK, SI)
      use iso_fortran_env, only: real64, int32, int64, real128
      integer, intent(in) :: I
      integer, intent(in) :: J
      integer, intent(in) :: K
      integer, intent(in) :: L
      integer, intent(in) :: M
      integer, intent(in) :: N
      integer, intent(in) :: ITIK
      real(kind=real64), intent(out) :: SI
!VAST.../CONSTS/ ZERO(IN), ONE(IN)
!VAST...Calls: IXJTIK, SIXJ5, SIXJ1, SIXJ35, SIXJ2, GRACAH1
!VAST...Calls: SIXJ3, SIXJ4
      end subroutine
      end interface
      end module
