      module sixj4_I
      interface
!...Generated by Pacific-Sierra Research 77to90 4.3E  10:06:26  11/16/01
      subroutine sixj4 (JC, JE, JD, JB, JF, ITIK, SI)
      use iso_fortran_env, only: real64, int32, int64, real128
      integer, intent(in) :: JC
      integer, intent(in) :: JE
      integer, intent(in) :: JD
      integer, intent(in) :: JB
      integer, intent(in) :: JF
      integer, intent(in) :: ITIK
      real(kind=real64), intent(out) :: SI
!VAST.../CONSTS/ ZERO(IN), HALF(IN), ONE(IN), TWO(IN), THREE(IN)
!VAST.../CONSTS/ EPS(IN)
!VAST...Calls: IXJTIK, GRACAH1, SIXJ2, SIXJ3
      end subroutine
      end interface
      end module
