      module snrc_I
      interface
!...Generated by Pacific-Sierra Research 77to90  4.3E  06:33:54  12/28/06
!...Modified by Charlotte Froese Fischer
!                     Gediminas Gaigalas  10/05/17
      subroutine snrc (IS, KAPS, KS, ND1, ND2, NE1, NE2, IBRD, IBRE)
      integer, dimension(4), intent(in) :: IS
      integer, dimension(4), intent(in) :: KAPS
      integer, dimension(4), intent(in) :: KS
      integer, intent(out) :: ND1
      integer, intent(out) :: ND2
      integer, intent(out) :: NE1
      integer, intent(out) :: NE2
      integer, intent(out) :: IBRD
      integer, intent(out) :: IBRE
      end subroutine
      end interface
      end module
