      module arctan_I
      interface
!...Generated by Pacific-Sierra Research 77to90  4.3E  10:46:34   2/14/04
!...Modified by Charlotte Froese Fischer
!                     Gediminas Gaigalas  10/05/17
      real(kind=real64) FUNCTION arctan (ARG1, ARG2)
      use iso_fortran_env, only: real64, int32, int64, real128
      real(kind=real64), intent(in) :: ARG1
      real(kind=real64), intent(in) :: ARG2
!VAST.../DEF9/ PI(IN)
      END FUNCTION
      end interface
      end module
