      module calen_I
      interface
!...Generated by Pacific-Sierra Research 77to90  4.3E  10:46:38   2/14/04
!...Modified by Charlotte Froese Fischer
!                     Gediminas Gaigalas  10/05/17
      subroutine calen (JTIME, JDATE)
      character(LEN=10)  :: JTIME
      character(LEN=8)  :: JDATE
      end subroutine
      end interface
      end module
