      MODULE cgamma_I
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  10:46:48   2/14/04
!...Modified by Charlotte Froese Fischer
!                     Gediminas Gaigalas  10/05/17
      SUBROUTINE cgamma (ARGR, ARGI, RESR, RESI)
      use iso_fortran_env, only: real64, int32, int64, real128
      real(real64), INTENT(IN) :: ARGR
      real(real64), INTENT(IN) :: ARGI
      real(real64), INTENT(OUT) :: RESR
      real(real64), INTENT(OUT) :: RESI
!VAST.../DEF0/ EXPMAX(IN), EXPMIN(IN), PRECIS(IN)
!VAST.../DEF9/ PI(IN)
!VAST...Calls: ARCTAN
!...This routine performs I/O.
      END SUBROUTINE
      END INTERFACE
      END MODULE
