module clrx_I
      implicit none
      interface
            ! ...Generated by Pacific-Sierra Research 77to90  4.3E  10:46:52   2/14/04
            ! ...Modified by Charlotte Froese Fischer
            !                     Gediminas Gaigalas  10/05/17
            function clrx(KAPPAA, K, KAPPAB) result(res)
            use, intrinsic :: iso_fortran_env, only: real64
            integer, parameter :: MFACT = 500
            integer, intent(in) :: KAPPAA
            integer, intent(in) :: K
            integer, intent(in) :: KAPPAB
            real(kind=real64)   :: res
            end function clrx
      end interface
end module clrx_I

