      module convrt2_I
      interface
!...Generated by Pacific-Sierra Research 77to90  4.3E  10:46:54   2/14/04
!...Modified by Charlotte Froese Fischer
!                     Gediminas Gaigalas  10/05/17
      subroutine convrt2 (INTNUM, CNUM, LENTH, FROM)
      integer, intent(in) :: INTNUM
      character (LEN = *), INTENT(INOUT) :: CNUM
      integer, intent(out) :: LENTH
      character (LEN = *), intent(in) :: FROM
!VAST.../IOUNIT/ ISTDE(IN)
!...This routine performs I/O.
      end subroutine
      end interface
      end module
