      module convrt_DOUBLE_I
      interface
!...Generated by Pacific-Sierra Research 77to90  4.3E  10:46:53   2/14/04
!...Modified by Charlotte Froese Fischer
!                     Gediminas Gaigalas  10/05/17
      subroutine convrt_double (INTNUM, CNUM, LENTH)
      integer, intent(in) :: INTNUM
      character (LEN = *), INTENT(INOUT) :: CNUM
      integer, intent(out) :: LENTH
!...This routine performs I/O.
      end subroutine
      end interface
      end module
