      module cre_I
      use iso_fortran_env, only: real64
      interface
!...Generated by Pacific-Sierra Research 77to90  4.3E  10:47:10   2/14/04
!...Modified by Charlotte Froese Fischer
!                     Gediminas Gaigalas  10/05/17
      real(kind=real64) FUNCTION cre (KAP1, K, KAP2)
      integer, INTENT(IN) :: KAP1
      integer :: K
      integer, INTENT(IN) :: KAP2
!VAST...Calls: CLRX
      END FUNCTION
      END interface
      end module
