      MODULE dcbsrw_I
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  10:47:15   2/14/04
!...Modified by Charlotte Froese Fischer
!                     Gediminas Gaigalas  10/05/17
      SUBROUTINE dcbsrw (N, KAPPA, Z, E, RG0, RG, RF, MTP)
      use iso_fortran_env, only: real64, int32, int64, real128
      USE parameter_def, ONLY: NNNP
      INTEGER, INTENT(IN) :: N
      INTEGER, INTENT(IN) :: KAPPA
      real(real64), INTENT(IN) :: Z
      real(real64), INTENT(OUT) :: E
      real(real64), INTENT(OUT) :: RG0
      real(real64), DIMENSION(NNNP), INTENT(INOUT) :: RG
      real(real64), DIMENSION(NNNP), INTENT(OUT) :: RF
      INTEGER, INTENT(OUT) :: MTP
!VAST.../DEF2/ C(IN)
!VAST.../DEF4/ ACCY(IN)
!VAST.../GRID/ R(IN), NTP(IN)
!VAST.../TATB/ TA(INOUT), TB(INOUT)
!VAST...Calls: CGAMMA
!...This routine performs I/O.
      END SUBROUTINE
      END INTERFACE
      END MODULE
