      module dcbsrw_I
      interface
!...Generated by Pacific-Sierra Research 77to90  4.3E  10:47:15   2/14/04
!...Modified by Charlotte Froese Fischer
!                     Gediminas Gaigalas  10/05/17
      subroutine dcbsrw (N, KAPPA, Z, E, RG0, RG, RF, MTP)
      use iso_fortran_env, only: real64, int32, int64, real128
      use parameter_def, only: NNNP
      integer, intent(in) :: N
      integer, intent(in) :: KAPPA
      real(real64), intent(in) :: Z
      real(real64), intent(out) :: E
      real(real64), intent(out) :: RG0
      real(real64), dimension(NNNP), INTENT(INOUT) :: RG
      real(real64), dimension(NNNP), intent(out) :: RF
      integer, intent(out) :: MTP
!VAST.../DEF2/ C(IN)
!VAST.../DEF4/ ACCY(IN)
!VAST.../GRID/ R(IN), NTP(IN)
!VAST.../TATB/ TA(INOUT), TB(INOUT)
!VAST...Calls: CGAMMA
!...This routine performs I/O.
      end subroutine
      end interface
      end module
