      module dinit_I
      interface
!...Generated by Pacific-Sierra Research 77to90  4.3E  10:47:18   2/14/04
!...Modified by Charlotte Froese Fischer
!                     Gediminas Gaigalas  10/05/17
      subroutine dinit (N, A, X, INCX)
      use iso_fortran_env, only: real64, int32, int64, real128
      integer, intent(in) :: N
      real(real64), intent(in) :: A
      real(real64), dimension(*), intent(out) :: X
      integer, intent(in) :: INCX
      end subroutine
      end interface
      end module
