      MODULE dinit_I
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  10:47:18   2/14/04
!...Modified by Charlotte Froese Fischer
!                     Gediminas Gaigalas  10/05/17
      SUBROUTINE dinit (N, A, X, INCX)
      use iso_fortran_env, only: real64, int32, int64, real128
      INTEGER, INTENT(IN) :: N
      real(real64), INTENT(IN) :: A
      real(real64), DIMENSION(*), INTENT(OUT) :: X
      INTEGER, INTENT(IN) :: INCX
      END SUBROUTINE
      END INTERFACE
      END MODULE
