      MODULE dmerge_I
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  10:47:20   2/14/04
!...Modified by Charlotte Froese Fischer
!                     Gediminas Gaigalas  10/05/17
      SUBROUTINE dmerge (N, DB, DC, IDY, DA, DCONST, DL)
      use iso_fortran_env, only: real64, int32, int64, real128
      INTEGER, INTENT(IN) :: N
      real(real64), DIMENSION(*), INTENT(IN) :: DB
      real(real64), DIMENSION(*), INTENT(INOUT) :: DC
      INTEGER, DIMENSION(N), INTENT(IN) :: IDY
      real(real64), DIMENSION(N), INTENT(IN) :: DA
      real(real64), INTENT(IN) :: DCONST
      real(real64), INTENT(OUT) :: DL
      END SUBROUTINE
      END INTERFACE
      END MODULE
