      module dmerge_I
      interface
!...Generated by Pacific-Sierra Research 77to90  4.3E  10:47:20   2/14/04
!...Modified by Charlotte Froese Fischer
!                     Gediminas Gaigalas  10/05/17
      subroutine dmerge (N, DB, DC, IDY, DA, DCONST, DL)
      use iso_fortran_env, only: real64, int32, int64, real128
      integer, intent(in) :: N
      real(kind=real64), dimension(*), intent(in) :: DB
      real(kind=real64), dimension(*), INTENT(INOUT) :: DC
      integer, dimension(N), intent(in) :: IDY
      real(kind=real64), dimension(N), intent(in) :: DA
      real(kind=real64), intent(in) :: DCONST
      real(kind=real64), intent(out) :: DL
      end subroutine
      end interface
      end module
