      MODULE draw_I
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  10:47:22   2/14/04
!...Modified by Charlotte Froese Fischer
!                     Gediminas Gaigalas  10/05/17
      SUBROUTINE draw (P, SP, Q, SQ, MF)
      use iso_fortran_env, only: real64, int32, int64, real128
      USE parameter_def, ONLY: NNNP
      real(real64), DIMENSION(NNNP), INTENT(IN) :: P
      real(real64), INTENT(IN) :: SP
      real(real64), DIMENSION(NNNP), INTENT(IN) :: Q
      real(real64), INTENT(IN) :: SQ
      INTEGER, INTENT(IN) :: MF
!VAST.../GRID/ R(IN), N(IN)
!...This routine performs I/O.
      END SUBROUTINE
      END INTERFACE
      END MODULE
