      module draw_I
      interface
!...Generated by Pacific-Sierra Research 77to90  4.3E  10:47:22   2/14/04
!...Modified by Charlotte Froese Fischer
!                     Gediminas Gaigalas  10/05/17
      subroutine draw (P, SP, Q, SQ, MF)
      use iso_fortran_env, only: real64, int32, int64, real128
      use parameter_def, only: NNNP
      real(kind=real64), dimension(NNNP), intent(in) :: P
      real(kind=real64), intent(in) :: SP
      real(kind=real64), dimension(NNNP), intent(in) :: Q
      real(kind=real64), intent(in) :: SQ
      integer, intent(in) :: MF
!VAST.../GRID/ R(IN), N(IN)
!...This routine performs I/O.
      end subroutine
      end interface
      end module
