      module ichkq2_I
      interface
!...Generated by Pacific-Sierra Research 77to90  4.3E  10:48:21   2/14/04
!...Modified by Charlotte Froese Fischer
!                     Gediminas Gaigalas  10/05/17
      integer FUNCTION ichkq2 (JA, JB)
      integer :: JA
      integer :: JB
!VAST.../ORB2/ NW(IN)
!VAST...Calls: IQ
      END FUNCTION
      end interface
      end module
