      module icopy_I
      interface
!...Generated by Pacific-Sierra Research 77to90  4.3E  10:48:29   2/14/04
!...Modified by Charlotte Froese Fischer
!                     Gediminas Gaigalas  10/05/17
      subroutine icopy (N, IX, INCX, IY, INCY)
      integer, intent(in) :: N
      integer, dimension(*), intent(in) :: IX
      integer :: INCX
!VAST...Dummy argument INCX is not referenced in this routine.
      integer, dimension(*), intent(out) :: IY
      integer :: INCY
!VAST...Dummy argument INCY is not referenced in this routine.
      end subroutine
      end interface
      end module
