      module iniest2_I
      interface
!...Generated by Pacific-Sierra Research 77to90  4.3E  12:36:59   2/14/04
!...Modified by Charlotte Froese Fischer
!                     Gediminas Gaigalas  10/05/17
      subroutine iniest2 (NMAX, NCF, NIV, BASIS, HMX, JCOL, IROW)
      use iso_fortran_env, only: real64, int32, int64, real128
      integer, intent(in) :: NMAX
      integer, intent(in) :: NCF
      integer, intent(in) :: NIV
      real(real64), dimension(*) :: BASIS
      real(real64), dimension(*), intent(in) :: HMX
      integer, dimension(0:*), intent(in) :: JCOL
      integer, dimension(*), intent(in) :: IROW
!VAST...Calls: ALLOC, DINIT, DSPEVX, DCOPY, DALLOC
      end subroutine
      end interface
      end module
