      MODULE iniest2_I
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  12:36:59   2/14/04
!...Modified by Charlotte Froese Fischer
!                     Gediminas Gaigalas  10/05/17
      SUBROUTINE iniest2 (NMAX, NCF, NIV, BASIS, HMX, JCOL, IROW)
      use iso_fortran_env, only: real64, int32, int64, real128
      INTEGER, INTENT(IN) :: NMAX
      INTEGER, INTENT(IN) :: NCF
      INTEGER, INTENT(IN) :: NIV
      real(real64), DIMENSION(*) :: BASIS
      real(real64), DIMENSION(*), INTENT(IN) :: HMX
      INTEGER, DIMENSION(0:*), INTENT(IN) :: JCOL
      INTEGER, DIMENSION(*), INTENT(IN) :: IROW
!VAST...Calls: ALLOC, DINIT, DSPEVX, DCOPY, DALLOC
      END SUBROUTINE
      END INTERFACE
      END MODULE
