      MODULE interp_I
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  10:48:32   2/14/04
!...Modified by Charlotte Froese Fischer
!                     Gediminas Gaigalas  10/05/17
      SUBROUTINE interp (XARR, YARR, NARR, XVAL, YVAL, ACCY)
      use iso_fortran_env, only: real64, int32, int64, real128
      INTEGER MXORD
      PARAMETER (MXORD = 11)
      real(real64), DIMENSION(NARR), INTENT(IN) :: XARR
      real(real64), DIMENSION(NARR), INTENT(IN) :: YARR
      INTEGER, INTENT(IN) :: NARR
      real(real64), INTENT(IN) :: XVAL
      real(real64), INTENT(OUT) :: YVAL
      real(real64), INTENT(IN) :: ACCY
!...This routine performs I/O.
      END SUBROUTINE
      END INTERFACE
      END MODULE
