      MODULE intrpq_I
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  15:33:45   2/14/04
!...Modified by Charlotte Froese Fischer
!                     Gediminas Gaigalas  10/05/17
      SUBROUTINE intrpq (PA, QA, MA, RA, J, DNORM)
      use iso_fortran_env, only: real64, int32, int64, real128
      INTEGER MXORD
      PARAMETER (MXORD = 13)
      real(real64), DIMENSION(*), INTENT(IN) :: PA, QA, RA
      INTEGER, INTENT(IN) :: MA
      INTEGER, INTENT(IN) :: J
      real(real64), INTENT(OUT) :: DNORM
      END SUBROUTINE
      END INTERFACE
      END MODULE
