      module intrpq_I
      interface
!...Generated by Pacific-Sierra Research 77to90  4.3E  15:33:45   2/14/04
!...Modified by Charlotte Froese Fischer
!                     Gediminas Gaigalas  10/05/17
      subroutine intrpq (PA, QA, MA, RA, J, DNORM)
      use iso_fortran_env, only: real64, int32, int64, real128
      integer MXORD
      parameter (MXORD = 13)
      real(real64), dimension(*), intent(in) :: PA, QA, RA
      integer, intent(in) :: MA
      integer, intent(in) :: J
      real(real64), intent(out) :: DNORM
      end subroutine
      end interface
      end module
