      module iq_I
      interface
!...Generated by Pacific-Sierra Research 77to90  4.3E  10:48:38   2/14/04
!...Modified by Charlotte Froese Fischer
!                     Gediminas Gaigalas  10/05/17
      integer FUNCTION iq (ISUBSH, ICSF)
      integer, intent(in) :: ISUBSH
      integer :: ICSF
!VAST...Calls: IQA
      END FUNCTION
      end interface
      end module
