      module itrig_I
      interface
!...Generated by Pacific-Sierra Research 77to90  4.3E  10:48:47   2/14/04
!...Modified by Charlotte Froese Fischer
!                     Gediminas Gaigalas  10/05/17
      integer FUNCTION itrig (I1, I2, I3)
      integer, intent(in) :: I1
      integer, intent(in) :: I2
      integer, intent(in) :: I3
      END FUNCTION
      end interface
      end module
