      module ldigit_I
      interface
!...Generated by Pacific-Sierra Research 77to90  4.3E  10:48:52   2/14/04
!...Modified by Charlotte Froese Fischer
!                     Gediminas Gaigalas  10/05/17
      logical FUNCTION ldigit (CST)
      character (LEN = 1), intent(in) :: CST
      END FUNCTION
      end interface
      end module
