      module lodcsh2_I
      interface
!...Generated by Pacific-Sierra Research 77to90  4.3E  10:49:02   2/14/04
!...Modified by Charlotte Froese Fischer
!                     Gediminas Gaigalas  10/05/17
      subroutine lodcsh2(NFILE, NCORE, JB)
      integer, intent(in) :: NFILE
      integer, intent(out) :: NCORE
      integer , intent(in) :: JB
      end subroutine
      end interface
      end module
