      module ltab_I
      interface
!...Generated by Pacific-Sierra Research 77to90  4.3E  10:49:59   2/14/04
!...Modified by Charlotte Froese Fischer
!                     Gediminas Gaigalas  10/05/17
      subroutine ltab (IS, NQS, KS, IROWS)
      integer, dimension(4), intent(in) :: IS
      integer, dimension(4), INTENT(INOUT) :: NQS
      integer, dimension(4), intent(in) :: KS
      integer, dimension(4), INTENT(INOUT) :: IROWS
!VAST.../TERMS/ NROWS(IN)
!...This routine performs I/O.
      end subroutine
      end interface
      end module
