      module nucpot_I
      interface
!...Generated by Pacific-Sierra Research 77to90  4.3E  10:50:02   2/14/04
!...Modified by Charlotte Froese Fischer
!                     Gediminas Gaigalas  10/05/17
      subroutine nucpot
!VAST.../DEBUGR/ LDBPR(IN)
!VAST.../DEF1/ Z(IN)
!VAST.../DEF9/ PI(IN)
!VAST.../GRID/ R(IN), N(IN)
!VAST.../NPAR/ PARM(IN), NPARM(IN)
!VAST.../NPOT/ ZZ(INOUT), NNUC(OUT)
!VAST...Calls: ES
!...This routine performs I/O.
      end subroutine
      end interface
      end module
