      module prsrsl_I
      interface
!...Generated by Pacific-Sierra Research 77to90  4.3E  10:50:16   2/14/04
!...Modified by Charlotte Froese Fischer
!                     Gediminas Gaigalas  10/05/17
      subroutine prsrsl (NFILE, ID)
      integer, intent(in) :: NFILE
      integer, intent(in) :: ID
!VAST.../IOUNIT/ ISTDE(IN)
!VAST.../ORB2/ NW(INOUT)
!VAST.../ORB4/ NP(INOUT), NAK(OUT)
!VAST.../ORB5/ NKL(OUT), NKJ(OUT)
!VAST.../ORB10/ NH(OUT)
!VAST...Calls: CONVRT
!...This routine performs I/O.
      end subroutine
      end interface
      end module
