      module prsrcn_I
      interface
!...Generated by Pacific-Sierra Research 77to90  4.3E  10:50:15   2/14/04
!...Modified by Charlotte Froese Fischer
!                     Gediminas Gaigalas  10/05/17
      subroutine prsrcn (RECORD, NCORE, IOCCS, IERR)
      use parameter_def, only: NNNW
      character (LEN = 256), intent(in) :: RECORD
      integer, intent(in) :: NCORE
      integer, dimension(NNNW), intent(out) :: IOCCS
      integer, intent(out) :: IERR
!VAST.../ORB2/ NW(IN)
!VAST.../ORB4/ NP(IN)
!VAST.../ORB5/ NKJ(IN)
!VAST.../ORB10/ NH(IN)
!...This routine performs I/O.
      end subroutine
      end interface
      end module
