      module quad_I
      interface
!...Generated by Pacific-Sierra Research 77to90  4.3E  10:50:18   2/14/04
!...Modified by Charlotte Froese Fischer
!                     Gediminas Gaigalas  10/05/17
      subroutine quad (RESULT)
      use iso_fortran_env, only: real64, int32, int64, real128
      real(kind=real64), intent(out) :: RESULT
!VAST.../GRID/ R(IN), RP(IN)
!VAST.../NCC/ C1(IN), C2(IN), C3(IN), C4(IN)
!VAST.../TATB/ TA(INOUT), MTP(IN)
      end subroutine
      end interface
      end module
