      module radgrd_I
      interface
!...Generated by Pacific-Sierra Research 77to90  4.3E  10:50:19   2/14/04
!...Modified by Charlotte Froese Fischer
!                     Gediminas Gaigalas  10/05/17
      subroutine radgrd
!VAST.../DEBUGR/ LDBPR(IN)
!VAST.../DEF0/ PRECIS(IN)
!VAST.../GRID/ R(INOUT), RP(INOUT), RPOR(INOUT), RNT(IN)
!VAST.../GRID/ H(IN), HP(IN), N(IN)
!...This routine performs I/O.
      end subroutine
      end interface
      end module
