      module rint_I
      interface
!...Generated by Pacific-Sierra Research 77to90  4.3E  10:50:22   2/14/04
!...Modified by Charlotte Froese Fischer
!                     Gediminas Gaigalas  10/05/17
      real(real64) FUNCTION rint (I, J, K)
      integer, intent(in) :: I
      integer, intent(in) :: J
      integer, intent(in) :: K
      END FUNCTION
      end interface
      end module
