      module setcon_I
      interface
!...Generated by Pacific-Sierra Research 77to90  4.3E  10:50:28   2/14/04
!...Modified by Charlotte Froese Fischer
!                     Gediminas Gaigalas  10/05/17
      subroutine setcon
!VAST.../DEBUGG/ LDBPG(IN)
!VAST.../DEF3/ EMPAM(OUT), RBCM(OUT)
!VAST.../DEF9/ CVAC(OUT), PI(OUT)
!VAST.../DEF10/ AUCM(OUT), AUEV(OUT), CCMS(OUT), FASI(OUT)
!VAST.../DEF10/ FBSI(OUT)
!VAST.../DEF11/ FMTOAU(OUT), AUMAMU(OUT)
!...This routine performs I/O.
      end subroutine
      end interface
      end module
