      module setqic_I
      interface
!...Generated by Pacific-Sierra Research 77to90  4.3E  10:50:39   2/14/04
!...Modified by Charlotte Froese Fischer
!                     Gediminas Gaigalas  10/05/17
      subroutine setqic
!VAST.../CNC5/ CNC5C(OUT)
!VAST.../GRID/ H(IN)
!VAST.../CNC6/ CNC6C(OUT)
!VAST.../LIC13/ A13(OUT)
!VAST.../NCC/ C1(OUT), C2(OUT), C3(OUT), C4(OUT)
!VAST.../SBC/ C(OUT)
      end subroutine
      end interface
      end module
