      MODULE speak_I
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  15:59:36   2/14/04
!...Modified by Charlotte Froese Fischer
!                     Gediminas Gaigalas  10/05/17
      SUBROUTINE speak (JA, JB, IA1, IB1, IA2, IB2, K, X)
      use iso_fortran_env, only: real64, int32, int64, real128
      INTEGER, INTENT(IN) :: JA
      INTEGER, INTENT(IN) :: JB
      INTEGER, INTENT(IN) :: IA1
      INTEGER, INTENT(IN) :: IB1
      INTEGER, INTENT(IN) :: IA2
      INTEGER, INTENT(IN) :: IB2
      INTEGER, INTENT(IN) :: K
      real(real64), INTENT(IN) :: X
!VAST.../BUFFER/ NBDIM(IN), NVCOEF(INOUT)
!VAST.../DEBUG/ IBUG1(IN)
!VAST.../ORB4/ NP(IN)
!VAST.../ORB10/ NH(IN)
!VAST...Calls: ALCBUF
!...This routine performs I/O.
      END SUBROUTINE
      END INTERFACE
      END MODULE
