      module speak_I
      interface
!...Generated by Pacific-Sierra Research 77to90  4.3E  15:59:36   2/14/04
!...Modified by Charlotte Froese Fischer
!                     Gediminas Gaigalas  10/05/17
      subroutine speak (JA, JB, IA1, IB1, IA2, IB2, K, X)
      use iso_fortran_env, only: real64, int32, int64, real128
      integer, intent(in) :: JA
      integer, intent(in) :: JB
      integer, intent(in) :: IA1
      integer, intent(in) :: IB1
      integer, intent(in) :: IA2
      integer, intent(in) :: IB2
      integer, intent(in) :: K
      real(real64), intent(in) :: X
!VAST.../BUFFER/ NBDIM(IN), NVCOEF(INOUT)
!VAST.../DEBUG/ IBUG1(IN)
!VAST.../ORB4/ NP(IN)
!VAST.../ORB10/ NH(IN)
!VAST...Calls: ALCBUF
!...This routine performs I/O.
      end subroutine
      end interface
      end module
