      MODULE spicmv2_I
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  10:50:47   2/14/04
!...Modified by Charlotte Froese Fischer
!                     Gediminas Gaigalas  10/05/17
      SUBROUTINE spicmv2 (N, M, B, C)
      use iso_fortran_env, only: real64, int32, int64, real128
      INTEGER, INTENT(IN) :: N
      INTEGER, INTENT(IN) :: M
      real(real64), DIMENSION(N,M), INTENT(IN) :: B
      real(real64), DIMENSION(N,M), INTENT(INOUT) :: C
!VAST...Calls: DINIT, IENDC, EMT, DMERGE, IROW
      END SUBROUTINE
      END INTERFACE
      END MODULE
