      MODULE start_I
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  10:50:48   2/14/04
!...Modified by Charlotte Froese Fischer
!                     Gediminas Gaigalas  10/05/17
      SUBROUTINE start (IORB, ITYPE, P0, P, Q0, Q)
      use iso_fortran_env, only: real64, int32, int64, real128
      USE parameter_def,   ONLY: NNNP
      INTEGER, INTENT(IN) :: IORB
      INTEGER, INTENT(IN) :: ITYPE
      real(real64), INTENT(IN) :: P0
      real(real64), DIMENSION(NNNP), INTENT(INOUT) :: P
      real(real64), INTENT(OUT) :: Q0
      real(real64), DIMENSION(NNNP), INTENT(INOUT) :: Q
!VAST.../CNC6/ CNC6C(IN)
!VAST.../DEF1/ Z(IN)
!VAST.../DEF2/ C(IN)
!VAST.../DEF4/ ACCY(IN)
!VAST.../GRID/ R(IN), RP(IN)
!VAST.../NPAR/ NPARM(IN)
!VAST.../ORB1/ E(IN), GAMA(IN)
!VAST.../ORB4/ NP(IN), NAK(IN)
!VAST.../ORB10/ NH(IN)
!VAST.../POTE/ YP(IN), XP(IN), XQ(IN)
!VAST.../SCF2/ NDCOF(IN)
!VAST.../WAVE/ PZ(IN)
!VAST...Calls: NDA, DA, QF, PF
!...This routine performs I/O.
      END SUBROUTINE
      END INTERFACE
      END MODULE
