      module starttime_I
      interface
!...Generated by Pacific-Sierra Research 77to90  4.3E  10:50:49   2/14/04
!...Modified by Charlotte Froese Fischer
!                     Gediminas Gaigalas  10/05/17
      subroutine starttime (NCOUNT1, PROGNAME)
      integer :: NCOUNT1
      character (LEN = *), intent(in) :: PROGNAME
!VAST...Calls: DATE_AND_TIME, SYSTEM_CLOCK
!...This routine performs I/O.
      end subroutine
      end interface
      end module
