      module yzk_I
      interface
!...Generated by Pacific-Sierra Research 77to90  4.3E  10:51:01   2/14/04
!...Modified by Charlotte Froese Fischer
!                     Gediminas Gaigalas  10/05/17
      subroutine yzk (K, I, J)
      integer KLIMIT
      parameter(KLIMIT=20)
      integer, intent(in) :: K
      integer, intent(in) :: I
      integer, intent(in) :: J
!VAST.../CNC5/ CNC5C(IN)
!VAST.../DEF4/ ACCY(IN)
!VAST.../GRID/ R(IN), RP(IN), N(IN)
!VAST.../NCC/ C1(IN), C2(IN), C3(IN)
!VAST.../TATB/ MTP(OUT)
!VAST.../WAVE/ MF(IN)
!VAST...Calls: PF, QF
!...This routine performs I/O.
      end subroutine
      end interface
      end module
